name: example
homepage: https://www.github.com/modulovalue/flutter_apply
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>

environment:
  sdk: '>2.2.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_apply:
    path: ../

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  extra_pedantic: ^1.1.1+2